### ISSUE TITLE
User can create tasks for a todo list.

### ISSUE THREAD

**Issue by taylorjosephgriffin** [taylorjosephgriffin/react-todo#1]
![user can create tasks](https://user-images.githubusercontent.com/23637586/42736640-ebb399be-881d-11e8-98df-7f7318ff8ca8.png)

# 🤔 Motivation
User will be able to add tasks to a persisted list of todo tasks.

# 📈 Plan
Define a stateful class component that allows users to add tasks to a todo list. 

# ⛏ Implementation
- [x] Create a wireframe.
- [x] Create an index.html, styles.css and index.js and set up browserify to bundle js files. 
- [x] Define a form input functional component for adding tasks. 
- [x] Define a list component for listing creating tasks. 
- [x] Define a navigation component. 
- [x] Define an app class component for handling for submits and rendering components. 
- [x] Refactor code and enhance styling.

# Finished gif/screenshot
![user can create a task](https://user-images.githubusercontent.com/23637586/42738542-366c5d8a-883a-11e8-9b8a-1c48a85a3bec.gif)
